### ISSUE TITLE
ini bukan bug tapi cuma request

### ISSUE THREAD

**Issue by ben-dev2609** [RTechnoS/bot_tulis#1]
bang ada vesi node js nya ga?

**Comment by erzadev** [comment]
ikut nyari yg nodejs

**Comment by RTechnoS** [comment]
belum ada kak, kalo sempat akan dibuat

**Comment by ben-dev2609** [comment]
ok, ditunggu

**Comment by MFarelS** [comment]
> bang ada vesi node js nya ga?

Ini gw lagi ngembangin bro tapi butuh imagemagick
[https://GitHub.com/MFarelS/RajinNulis-BOT](https://GitHub.com/MFarelS/RajinNulis-BOT)
